name: 可能存在的问题报告
about: 提交在开发过程中未经或需要继续测试的潜在问题

body:
- type: input
  id: mayExistsIssues
  attributes:
    label: mayExistsIssues
    description: "描述可能存在的问题"
    placeholder: "内容..."
  validations:
    required: true
