name: Zipper
on:
  push:
    branches: ["master"]
jobs:
  zip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: run zipper.sh
        run: |
         /bin/bash ./zipper.sh
         git config --global user.name "Github Actions"
         git config --global user.email "actions@github.com"
         git add RIC.zip
         git commit --allow-empty -m "自动更新RIC.zip"
         git push
