name: Zipper
on:
  push:
    branches: ["master"]
jobs:
  zip:
    permissions:
      contents: write # for git push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: run Zipper.sh to update RIC.zip
        run: |
         /bin/bash ./Zipper.sh
         
         if [ -n "$(git status --porcelain)" ]; then
           git config --global user.name "Github Actions"
           git config --global user.email "actions@github.com"
           git add RIC.zip
           git commit --allow-empty -m "自动更新RIC.zip"
           git push
         fi
      - name: run UpgradeZipper to upgrade RIC_Upgrade.zip
        run: |
          /bin/bash ./UpgradeZipper.sh
          if [ -n "$(git status --porcelain)" ]; then
            git config --global user.name "Github Actions"
            git config --global user.email "actions@github.com"
            git add RIC_Upgrade.zip
            git commit --allow-empty -m "自动更新RIC_Upgrade.zip"
            git push
          fi
